import type { Exercise, WorkoutTemplate } from '../types';

export const EXERCISES: Exercise[] = [
  {
    id: 'ex_bench_press',
    name: 'Bench Press',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    category: 'strength',
    description: 'Classic compound chest exercise using a barbell on a flat bench.',
  },
  {
    id: 'ex_squat',
    name: 'Back Squat',
    muscleGroups: ['legs', 'glutes', 'core'],
    category: 'strength',
    description: 'King of lower body exercises — targets quads, hamstrings, and glutes.',
  },
  {
    id: 'ex_deadlift',
    name: 'Deadlift',
    muscleGroups: ['back', 'legs', 'glutes', 'core'],
    category: 'strength',
    description: 'Full body posterior chain exercise. Lift the bar from the floor.',
  },
  {
    id: 'ex_ohp',
    name: 'Overhead Press',
    muscleGroups: ['shoulders', 'triceps', 'core'],
    category: 'strength',
    description: 'Standing barbell press overhead — builds shoulder strength and stability.',
  },
  {
    id: 'ex_pullup',
    name: 'Pull-Up',
    muscleGroups: ['back', 'biceps'],
    category: 'strength',
    description: 'Bodyweight pulling movement. Great for back width and biceps.',
  },
  {
    id: 'ex_row',
    name: 'Barbell Row',
    muscleGroups: ['back', 'biceps'],
    category: 'strength',
    description: 'Horizontal pulling movement — builds back thickness.',
  },
  {
    id: 'ex_dips',
    name: 'Dips',
    muscleGroups: ['chest', 'triceps'],
    category: 'strength',
    description: 'Bodyweight pushing movement targeting chest and triceps.',
  },
  {
    id: 'ex_lunges',
    name: 'Lunges',
    muscleGroups: ['legs', 'glutes'],
    category: 'strength',
    description: 'Unilateral leg exercise improving balance and leg strength.',
  },
  {
    id: 'ex_plank',
    name: 'Plank',
    muscleGroups: ['core'],
    category: 'strength',
    description: 'Isometric core stabilization exercise.',
  },
  {
    id: 'ex_run',
    name: 'Running',
    muscleGroups: ['cardio', 'legs'],
    category: 'cardio',
    description: 'Outdoor or treadmill running for cardiovascular fitness.',
  },
  {
    id: 'ex_cycling',
    name: 'Cycling',
    muscleGroups: ['cardio', 'legs'],
    category: 'cardio',
    description: 'Cycling for endurance and lower body conditioning.',
  },
  {
    id: 'ex_curl',
    name: 'Bicep Curl',
    muscleGroups: ['biceps'],
    category: 'strength',
    description: 'Isolation exercise for the biceps using dumbbells or barbell.',
  },
  {
    id: 'ex_tricep_ext',
    name: 'Tricep Extension',
    muscleGroups: ['triceps'],
    category: 'strength',
    description: 'Overhead or cable extension targeting the triceps.',
  },
  {
    id: 'ex_lat_raise',
    name: 'Lateral Raise',
    muscleGroups: ['shoulders'],
    category: 'strength',
    description: 'Dumbbell side raises for shoulder width.',
  },
  {
    id: 'ex_hiit',
    name: 'HIIT Circuit',
    muscleGroups: ['full_body', 'cardio'],
    category: 'hiit',
    description: 'High intensity interval training — alternating bursts and rest.',
  },
];

export const WORKOUT_TEMPLATES: WorkoutTemplate[] = [
  {
    id: 'tpl_push',
    name: 'Push Day',
    description: 'Chest, shoulders, and triceps — classic push workout.',
    category: 'strength',
    difficulty: 'intermediate',
    estimatedDuration: 60,
    muscleGroups: ['chest', 'shoulders', 'triceps'],
    exercises: [
      { exercise: EXERCISES[0], defaultSets: 4, defaultReps: 8, defaultWeight: 60 },
      { exercise: EXERCISES[3], defaultSets: 3, defaultReps: 10, defaultWeight: 40 },
      { exercise: EXERCISES[6], defaultSets: 3, defaultReps: 12 },
      { exercise: EXERCISES[12], defaultSets: 3, defaultReps: 12, defaultWeight: 15 },
      { exercise: EXERCISES[13], defaultSets: 3, defaultReps: 15, defaultWeight: 10 },
    ],
  },
  {
    id: 'tpl_pull',
    name: 'Pull Day',
    description: 'Back and biceps — build a wide, thick back.',
    category: 'strength',
    difficulty: 'intermediate',
    estimatedDuration: 55,
    muscleGroups: ['back', 'biceps'],
    exercises: [
      { exercise: EXERCISES[4], defaultSets: 4, defaultReps: 8 },
      { exercise: EXERCISES[5], defaultSets: 4, defaultReps: 8, defaultWeight: 70 },
      { exercise: EXERCISES[11], defaultSets: 3, defaultReps: 12, defaultWeight: 15 },
    ],
  },
  {
    id: 'tpl_legs',
    name: 'Leg Day',
    description: 'Never skip leg day — quads, hamstrings, and glutes.',
    category: 'strength',
    difficulty: 'intermediate',
    estimatedDuration: 65,
    muscleGroups: ['legs', 'glutes', 'core'],
    exercises: [
      { exercise: EXERCISES[1], defaultSets: 4, defaultReps: 8, defaultWeight: 80 },
      { exercise: EXERCISES[2], defaultSets: 3, defaultReps: 5, defaultWeight: 100 },
      { exercise: EXERCISES[7], defaultSets: 3, defaultReps: 12, defaultWeight: 20 },
      { exercise: EXERCISES[8], defaultSets: 3, defaultDuration: 60 },
    ],
  },
  {
    id: 'tpl_cardio',
    name: 'Cardio Blast',
    description: '30-minute run + core finisher.',
    category: 'cardio',
    difficulty: 'beginner',
    estimatedDuration: 40,
    muscleGroups: ['cardio', 'core'],
    exercises: [
      { exercise: EXERCISES[9], defaultSets: 1, defaultDuration: 1800, defaultWeight: 0 },
      { exercise: EXERCISES[8], defaultSets: 3, defaultDuration: 60 },
    ],
  },
  {
    id: 'tpl_hiit',
    name: 'HIIT Circuit',
    description: 'Full body high intensity intervals — 20 minutes, maximum effort.',
    category: 'hiit',
    difficulty: 'advanced',
    estimatedDuration: 25,
    muscleGroups: ['full_body', 'cardio'],
    exercises: [
      { exercise: EXERCISES[14], defaultSets: 6, defaultDuration: 40 },
    ],
  },
];

export const MUSCLE_GROUP_LABELS: Record<string, string> = {
  chest: 'Chest',
  back: 'Back',
  shoulders: 'Shoulders',
  biceps: 'Biceps',
  triceps: 'Triceps',
  legs: 'Legs',
  glutes: 'Glutes',
  core: 'Core',
  cardio: 'Cardio',
  full_body: 'Full Body',
};

export const CATEGORY_LABELS: Record<string, string> = {
  strength: 'Strength',
  cardio: 'Cardio',
  flexibility: 'Flexibility',
  hiit: 'HIIT',
  custom: 'Custom',
};
